/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kenchoo (https://sketchfab.com/kenchoo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bicolor-cat-e623a618ca344a8393d7ba4d63ec23cf
Title: Bicolor Cat
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import { useEffect, useRef } from "react";

type P = ThreeElements["group"];

const CatModel: React.FC<P> = (props) => {
  const group = useRef<any>(null);
  const { nodes, materials, animations } = useGLTF("bicolor_cat.glb") as any;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Animation"]?.play?.();

    return () => {
      actions["Animation"]?.stop?.();
    };
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="cat_Rigao_41" scale={0.369}>
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.material}
                    skeleton={nodes.Object_7.skeleton}
                    morphTargetDictionary={nodes.Object_7.morphTargetDictionary}
                    morphTargetInfluences={nodes.Object_7.morphTargetInfluences}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.cat_diffuse}
                    skeleton={nodes.Object_8.skeleton}
                    morphTargetDictionary={nodes.Object_8.morphTargetDictionary}
                    morphTargetInfluences={nodes.Object_8.morphTargetInfluences}
                  />
                  <group name="cat_40" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("bicolor_cat.glb");

export default CatModel;
