/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Yu (https://sketchfab.com/FFT_kedar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cats-gajuannie-1646599e9b2845c7b2eddadc897edf37
Title: Cats (Gaju&Annie)
*/

import { useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import React from "react";

type P = ThreeElements["group"];

const CatsModel: React.FC<P> = (props) => {
  const { nodes, materials } = useGLTF("cats_gajuannie.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.model}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

export default CatsModel;

useGLTF.preload("cats_gajuannie.glb");
