/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-f844c0357d284fd8baa1435e9ff31bb2
Title: Retro computer
*/

import { useGLTF } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";
import React from "react";

type P = ThreeElements["group"];

const PcModel: React.FC<P> = (props) => {
  const { nodes, materials } = useGLTF("imac_computer.glb") as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.005}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Display_iMac_0.geometry}
            material={materials.iMac}
            position={[2.684, 83.159, 64.775]}
            rotation={[-1.484, 0, -Math.PI]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Base_Base_0.geometry}
            material={materials.Base}
            position={[2.684, -0.125, 67.889]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Keyboard_Keyboard_0.geometry}
            material={materials.Keyboard}
            position={[22.163, 1.566, -0.477]}
            rotation={[-1.58, 0, 3.139]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mouse001_Mouse_0.geometry}
            material={materials.Mouse}
            position={[-49.729, 1.055, 2.455]}
            rotation={[-Math.PI / 2, 0, 0.023]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
};
export default PcModel;
useGLTF.preload("imac_computer.glb");
